#!/bin/bash
mkdir -p log

# Source: 脚本_omni_anomaly.sh command 18 (self_impl.OmniAnomaly_disco)
nohup python -u ./scripts/run_benchmark.py \
    --config-path "unfixed_detect_score_multi_config.json" \
    --data-name-list "SWAT.csv" \
    --model-name "self_impl.OmniAnomaly_disco" \
    --model-hyper-params '{"seq_len":100,"batch_size":50,"num_epochs":10,"lr":0.001,"hidden_dim":500,"dense_dim":500,"z_dim":3,"beta":1.0,"posterior_flow_type":"nf","nf_layers":20,"std_epsilon":0.0001,"patience":5,"train_val_ratio":0.7,"gradient_clip_norm":10.0,"score_normalize":true,"score_source":"last_nll","anomaly_ratio":5.0,"enable_spl":true,"spl_mode":"easy_first","spl_active_lr_scale":0.2,"spl_start_epoch":4,"spl_cooldown_epochs":2,"spl_min_weight":0.995,"spl_init_weight":0.4,"spl_target_quantile":0.6,"spl_gamma":0.7,"spl_temperature":3.0,"spl_difficulty_source":"last_nll","spl_blowup_ratio":1.05,"spl_stop_on_fuse":true,"score_variants":[{"name":"last_nll","score_source":"last_nll","score_source_secondary":null,"score_source_fusion":"raw","score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"meanmax_guard005","score_source":"meanmax_nll","score_source_secondary":"last_nll","score_source_fusion":"rank","score_source_blend":0.05,"score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"meanmax_guard010","score_source":"meanmax_nll","score_source_secondary":"last_nll","score_source_fusion":"rank","score_source_blend":0.1,"score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"meanmax_guard015","score_source":"meanmax_nll","score_source_secondary":"last_nll","score_source_fusion":"rank","score_source_blend":0.15,"score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"meanmax_guard020","score_source":"meanmax_nll","score_source_secondary":"last_nll","score_source_fusion":"rank","score_source_blend":0.2,"score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"last_sharp001","score_source":"last_nll","score_source_secondary":null,"score_source_fusion":"raw","score_smooth_window":21,"score_smooth_blend":-0.01,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"last_sharp002","score_source":"last_nll","score_source_secondary":null,"score_source_fusion":"raw","score_smooth_window":21,"score_smooth_blend":-0.02,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"last_rollmax001","score_source":"last_nll","score_source_secondary":null,"score_source_fusion":"raw","score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":7,"score_rollmax_blend":0.01,"score_window_agg":"last"},{"name":"last_rollmax002","score_source":"last_nll","score_source_secondary":null,"score_source_fusion":"raw","score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":7,"score_rollmax_blend":0.02,"score_window_agg":"last"}]}' \
    --gpus 5 --num-workers 1 --timeout 60000 \
    --save-path "score/OmniAnomaly_disco" > log/score_swat_omni_anomaly_disco.log 2>&1 &

# Source: 脚本_omni_swat_score_disco.sh command 1 (self_impl.OmniAnomaly_disco)
nohup python -u ./scripts/run_benchmark.py \
    --config-path "unfixed_detect_score_multi_config_roc_pr.json" \
    --data-name-list "SWAT.csv" \
    --model-name "self_impl.OmniAnomaly_disco" \
    --model-hyper-params '{"seq_len":100,"batch_size":50,"num_epochs":10,"lr":0.001,"hidden_dim":500,"dense_dim":500,"z_dim":3,"beta":1.0,"posterior_flow_type":"nf","nf_layers":20,"std_epsilon":0.0001,"patience":5,"train_val_ratio":0.7,"gradient_clip_norm":10.0,"score_normalize":true,"score_source":"last_nll","anomaly_ratio":5.0,"enable_spl":true,"spl_mode":"easy_first","spl_active_lr_scale":0.2,"spl_start_epoch":4,"spl_cooldown_epochs":2,"spl_min_weight":0.995,"spl_init_weight":0.4,"spl_target_quantile":0.6,"spl_gamma":0.7,"spl_temperature":3.0,"spl_difficulty_source":"last_nll","spl_blowup_ratio":1.05,"spl_stop_on_fuse":true,"score_variants":[{"name":"last_nll","score_source":"last_nll","score_source_secondary":null,"score_source_fusion":"raw","score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"meanmax_guard005","score_source":"meanmax_nll","score_source_secondary":"last_nll","score_source_fusion":"rank","score_source_blend":0.05,"score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"meanmax_guard010","score_source":"meanmax_nll","score_source_secondary":"last_nll","score_source_fusion":"rank","score_source_blend":0.1,"score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"meanmax_guard015","score_source":"meanmax_nll","score_source_secondary":"last_nll","score_source_fusion":"rank","score_source_blend":0.15,"score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"meanmax_guard020","score_source":"meanmax_nll","score_source_secondary":"last_nll","score_source_fusion":"rank","score_source_blend":0.2,"score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"last_sharp001","score_source":"last_nll","score_source_secondary":null,"score_source_fusion":"raw","score_smooth_window":21,"score_smooth_blend":-0.01,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"last_sharp002","score_source":"last_nll","score_source_secondary":null,"score_source_fusion":"raw","score_smooth_window":21,"score_smooth_blend":-0.02,"score_rollmax_window":1,"score_rollmax_blend":0.0,"score_window_agg":"last"},{"name":"last_rollmax001","score_source":"last_nll","score_source_secondary":null,"score_source_fusion":"raw","score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":7,"score_rollmax_blend":0.01,"score_window_agg":"last"},{"name":"last_rollmax002","score_source":"last_nll","score_source_secondary":null,"score_source_fusion":"raw","score_smooth_window":1,"score_smooth_blend":0.0,"score_rollmax_window":7,"score_rollmax_blend":0.02,"score_window_agg":"last"}]}' \
    --gpus 5 --num-workers 1 --timeout 60000 \
    --save-path "score/OmniAnomaly_disco" > log/score_swat_omni_anomaly_disco_active_lr.log 2>&1 &
